### ISSUE TITLE
Questions about the code and the paper

### ISSUE THREAD

**Issue by ShenhanQian** [FangyunWei/PointSetAnchor#1]
Your method achieve the best pose estimation performance on COCO dataset among all the methods based on offset-regression, congrats!

Then, here come some questions:

1. According to the code, it seems that you do heatmap regression along with offset regression, but this is not mentioned in the paper, why? How important is this part to the performance?
2. How did you choose the following parameter?
https://github.com/FangyunWei/PointSetAnchor/blob/e2527f167e04097f07e9f04f79f30cf15366714d/configs/point_set_anchor_pose/8GPUs_points_set_anchor_pose_HRNetw32_115E.py#L59
3. As we know that the mean pose is a good initial estimation, did you try to directly evaluate the mean pose, and compare the mAP with regression results from the center point or rectangle (like in Table 6)?
4. If I use an anchor-free detector like RepPoints or FCOS, and substitute the anchor poses in your model with a plain regression stage, can it achieve comparable performance in your model, what do you think?

Again, thanks very much for your time!

**Comment by FangyunWei** [comment]
Hi Shenhan,

Thanks for your interests in our project. For your questions:

1.  Actually we use heatmap for auxiliary training at the very first version. For final version, we did further experiments to fuse the regression results and heatmap pose. This will bring ~1.8 AP improvement. I agree we should claim this in our paper. I will update in next version in arxiv.

2. We didn't do such comparison.

3. I think it's very meaningful to do such experiments. Actually we find we do not need so many pointset anchors recently. Maybe you could replace center representation in FCOS to our pointset anchor and do such experiment. Hope you could share the results to me if you do so. Thanks.

Best,
Fangyun




On 08/10/2020 13:52, Qian Shenhan wrote:

We appreciate your efforts in the paper and the code. As far as I know, you have achieved the best pose estimation performance on COCO among all the methods based on offset-regression!

Then, I have some questions:

According to the code, it seems that you do heatmap regression along with offset regression, but this is not mentioned in the paper, why? How important is this part to the performance?
As we know that the mean pose is a good initial estimation, did you try to directly evaluate the mean pose, and compare the mAP with regression results from the center point or rectangle (like in Table 6)?
If I use an anchor-free detector like RepPoints or FCOS, and substitute the anchor poses in your model with a plain regression stage, can it achieve comparable performance in your model, what do you think?

Again, thanks very much for your time!

**Comment by ShenhanQian** [comment]
Thanks for your reply!

I'm still curious about two more questions:
1. Did you use a fusion method similar to [Object as Points](http://xxx.itp.ac.cn/abs/1904.07850) to fuse the predicted offset and heatmap?
2. As we know that the built-in DeformConv of MMDetection only supports an odd squared number of feature points, and your paper provides results with 9 and 25 points, this is reasonable.
But since the number of keypoints in COCO_person is only 17, how can you use 25 points? 
Meanwhile, when you use 9 points, how do you choose which points to use (as is shown in the code)?
https://github.com/FangyunWei/PointSetAnchor/blob/e2527f167e04097f07e9f04f79f30cf15366714d/configs/point_set_anchor_pose/8GPUs_points_set_anchor_pose_HRNetw32_115E.py#L59

Best regards!

**Comment by FangyunWei** [comment]
Hi

1.  As I stated in the last mail. Fusion will bring a 1.8 AP improvement. Just as in Centernet. We think learning a heatmap will bring meaningful features for feature aggregation.

2. We just randomly select 9 points from 17 pose points in 9 points setting and use 8 points two times (and thus the rest 9 points will be used only one time) in 25 points setting.

Best,
Fangyun




On 08/11/2020 20:15, Qian Shenhan wrote:

Thanks for your reply!

I'm still curious about two more questions:

Did you use a fusion method similar to Object as Points to fuse the predicted offset and heatmap?
As we know that the built-in DeformConv of MMDetection only supports an odd squared number of feature points, and your paper provides results with 9 and 25 points, this is reasonable.
But since the number of keypoints in COCO_person is only 17, how can you use 25 points?
Meanwhile, when you use 9 points, how do you choose which points to use (as is shown in the code)?
https://github.com/FangyunWei/PointSetAnchor/blob/e2527f167e04097f07e9f04f79f30cf15366714d/configs/point_set_anchor_pose/8GPUs_points_set_anchor_pose_HRNetw32_115E.py#L59

Best regards!

**Comment by ShenhanQian** [comment]
Thanks a lot!

**Comment by hellojialee** [comment]
@ShenhanQian Hi, what do you mean when you say "fuse the predicted offset and heatmap". Is it a feature map fusion or heatmap_peak_location + offset_regression = precise_coordinates?

**Comment by ShenhanQian** [comment]
As is stated in [Objects as Points](http://arxiv.org/pdf/1904.07850):
> We then snap our initial predictions to the closest detected keypoint on this heatmap. Here, our center offset
acts as a grouping cue, to assign individual keypoint detections to their closest person instance.

You can refer to **Section 4.2** for details.
